class Consts:
    HEADER_SIZE = 9
    TCP_HEADER_SIZE = 20
    MTU = 500
    DEAFULT_PORT = 11000
    DEFAILT_RECV_TIMEOUT = 0.5
    MAX_CHUNK_SIZE = 2048
    PAYLOAD_SIZE = MTU - TCP_HEADER_SIZE - HEADER_SIZE
    WINDOW_SIZE = 60
    MAX_PACKET_TIMEOUT = 20
    INIT_PACKET_TIMEOUT = 5
    TIMEOUT_STEP = 1
    GLOBAL_TIMEOUT = 10
    TIMEOUT_RESEND_GAP = 0.07
    FINALIZE_TIMEOUT = 3.5
    END_SEQ_NUM = 300
